INSERT INTO `users` (`id`, `login`, `password`, `firstname`, `lastname`, `email`, `langue`, `role`, `created_at`)
VALUES (1, 'bob', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Bob', 'Sull', 'bob@sull.com', 'fr',
        'admin', NOW()),
       (2, 'anna', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Anna', 'Lyse', 'anna.lyse@sull.com',
        'en', 'member', NOW()),
       (3, 'client1', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Cli', 'Ent',
        'contact@client.com', 'fr',
        'client', NOW()),
       (4, 'jean', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Jean', 'Dupont',
        'jean.dupont@example.com', 'fr', 'member', NOW()),
       (5, 'marie', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Marie', 'Curie',
        'marie.curie@example.com', 'fr', 'admin', NOW()),
       (6, 'alex', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Alexandre', 'Leroy',
        'alex.leroy@example.com', 'en', 'member', NOW()),
       (7, 'louis', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Louis', 'Pasteur',
        'louis.pasteur@example.com', 'fr', 'client', NOW()),
       (8, 'sophie', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Sophie', 'Marceau',
        'sophie.marceau@example.com', 'en', 'member', NOW()),
       (9, 'pierre', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Pierre', 'Curie',
        'pierre.curie@example.com', 'fr', 'client', NOW()),
       (10, 'nicolas', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Nicolas', 'Cage',
        'nicolas.cage@example.com', 'en', 'member', NOW());
