INSERT INTO `users`
(`id`, `login`, `password`, `firstname`, `lastname`, `email`, `type_client`, `nom_entreprise`, `tva`, `telephone`,
 `adresse`, `langue`, `role`, `created_at`)
VALUES (1, 'bob', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Bob', 'Sull', 'bob@sull.com',
        'particulier', NULL, NULL, '0123456789', '1 rue de Bob', 'fr', 'ADMIN', NOW()),
       (2, 'anna', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Anna', 'Lyse', 'anna.lyse@sull.com',
        'particulier', NULL, NULL, '0123456780', '2 rue de Anna', 'en', 'MEMBER', NOW()),
       (3, 'client1', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Cli', 'Ent',
        'contact@client.com', 'entreprise', 'Client1 SARL', 'FR123456789', '0123456781', '3 rue de Client1', 'fr',
        'CLIENT', NOW()),
       (4, 'jean', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Jean', 'Dupont',
        'jean.dupont@example.com', 'particulier', NULL, NULL, '0123456782', '4 rue de Jean', 'fr', 'MEMBER', NOW()),
       (5, 'marie', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Marie', 'Curie',
        'marie.curie@example.com', 'particulier', NULL, NULL, '0123456783', '5 rue de Marie', 'fr', 'ADMIN', NOW()),
       (6, 'alex', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Alexandre', 'Leroy',
        'alex.leroy@example.com', 'particulier', NULL, NULL, '0123456784', '6 rue d''Alex', 'en', 'MEMBER', NOW()),
       (7, 'louis', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Louis', 'Pasteur',
        'louis.pasteur@example.com', 'particulier', NULL, NULL, '0123456785', '7 rue de Louis', 'fr', 'CLIENT', NOW()),
       (8, 'sophie', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Sophie', 'Marceau',
        'sophie.marceau@example.com', 'particulier', NULL, NULL, '0123456786', '8 rue de Sophie', 'en', 'MEMBER',
        NOW()),
       (9, 'pierre', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Pierre', 'Curie',
        'pierre.curie@example.com', 'entreprise', 'Pierre SARL', 'FR987654321', '0123456787', '9 rue de Pierre', 'fr',
        'CLIENT', NOW()),
       (10, 'nicolas', '$2a$12$EyDxX5wWsrJGIyo2MFIRR.LqLmmqssUdPgwasMrG7TvZmjW9ECeLW', 'Nicolas', 'Cage',
        'nicolas.cage@example.com', 'particulier', NULL, NULL, '0123456788', '10 rue de Nicolas', 'en', 'MEMBER',
        NOW());
